import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import ClientProvider from "@/components/ClientProvider";
import { getServerSession } from "next-auth/next";

export const metadata: Metadata = {
	title: "Meta Messenger",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession();

	return (
		<html lang="en">
			<body>
				<Header />
				<ClientProvider session={session}>{children}</ClientProvider>
			</body>
		</html>
	);
}
